// 공통 데이터: 캐릭터, 게임, 차시 정보
window.CHARACTERS = [
  {
    id: 'badoogi',
    name: '바두기',
    species: '강아지',
    img: 'assets/characters/badoogi.png',
    color: '#2A2A2A',
    bg: '#F4F4F4',
    accent: '#FFB6C1',
    role: '든든한 친구',
    tag: '호기심 가득',
    quote: '같이 풀어볼래?',
  },
  {
    id: 'soondal',
    name: '순달',
    species: '수달',
    img: 'assets/characters/soondal.png',
    color: '#7B8FA8',
    bg: '#E8EEF4',
    accent: '#A5C8E0',
    role: '긍정 에너지',
    tag: '따뜻한 마음',
    quote: '천천히 함께 가자!',
  },
  {
    id: 'dalgom',
    name: '달곰',
    species: '반달곰',
    img: 'assets/characters/dalgom.png',
    color: '#8B6F4E',
    bg: '#F4ECDF',
    accent: '#D9B382',
    role: '분석 탐정',
    tag: '반짝이는 아이디어',
    quote: '단서를 찾아볼까?',
  },
  {
    id: 'ssaksu',
    name: '싹수',
    species: '아이디어 친구',
    img: 'assets/characters/ssaksu.png',
    color: '#D9A300',
    bg: '#FFF6D6',
    accent: '#FFD84D',
    role: '아이디어 메이커',
    tag: '쑥쑥 자라는',
    quote: '와! 이건 어때?',
  },
  {
    id: 'yeoul',
    name: '여울',
    species: '여우',
    img: 'assets/characters/yeoul.png',
    color: '#E8732C',
    bg: '#FFE8D6',
    accent: '#FFAA6B',
    role: '용감한 리더',
    tag: '용기 있는',
    quote: '함께 도전하자!',
  },
];

window.LESSONS = [
  { id: 1, title: '약수', subtitle: '나누어떨어지는 수', icon: '🍰', color: '#FFB6C1', mascot: 'dalgom',
    objective: '주어진 수를 나누어떨어지게 하는 약수를 찾을 수 있다.' },
  { id: 2, title: '배수', subtitle: '곱해서 만든 수', icon: '🚀', color: '#A5C8E0', mascot: 'yeoul',
    objective: '주어진 수의 배수를 차례로 구할 수 있다.' },
  { id: 3, title: '최대공약수', subtitle: '함께 나누는 가장 큰 수', icon: '🔍', color: '#FFD84D', mascot: 'ssaksu',
    objective: '두 수의 공통 약수 중 가장 큰 수를 찾을 수 있다.' },
  { id: 4, title: '최소공배수', subtitle: '함께 만나는 가장 작은 수', icon: '✨', color: '#FFAA6B', mascot: 'soondal',
    objective: '두 수의 공통 배수 중 가장 작은 수를 찾을 수 있다.' },
];

window.GAMES = [
  { id: 'card-flip', title: '뒤집기 카드',  desc: '같은 약수를 가진 짝을 찾아라!',
    icon: '🃏', color: '#FFB6C1', topics: [1,3], mascot: 'badoogi', difficulty: '쉬움', players: '1~2인' },
  { id: 'card-pick', title: '카드 고르기',   desc: '조건에 맞는 카드를 골라봐!',
    icon: '🎴', color: '#FFD84D', topics: [1,2], mascot: 'ssaksu', difficulty: '쉬움', players: '1인' },
  { id: 'frog',      title: '연못 건너기',   desc: '배수의 돌만 밟고 건너자!',
    icon: '🐸', color: '#A8D8B9', topics: [2,4], mascot: 'soondal', difficulty: '보통', players: '1인' },
  { id: 'galaga',    title: '약수 갤러그',   desc: '맞는 수를 쏴서 떨어뜨려!',
    icon: '🚀', color: '#A5C8E0', topics: [1,2,3,4], mascot: 'yeoul', difficulty: '도전', players: '1인' },
  { id: 'pacman',    title: '공배수 미로',   desc: '미로에서 공배수만 먹어라!',
    icon: '👾', color: '#FFAA6B', topics: [3,4], mascot: 'dalgom', difficulty: '도전', players: '1인' },
];
